# theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Chamali Vishmani Portfolio
description: Project and Information Portfolio
logo: /assets/imgs/official_photo.png
# show_downloads: true
